version: 2
jobs:
  build:
    docker:
      - image: circleci/python3
      - image: postgres:9.6
    steps:
      - checkout
      - run:
          name: view content
          command: ls
      - run:
          name: install python requirements
          command: pip3 install requirements.txt
